// File generated by FlutterFire CLI.
// This is a placeholder file. You need to:
// 1. Create a Firebase project at https://console.firebase.google.com
// 2. Add your app to the Firebase project (Android, iOS, Web, macOS)
// 3. Run `flutterfire configure` to generate this file with your actual config
// 4. Enable Firebase Authentication (Email/Password and Anonymous)
// 5. Create a Firestore database
// 6. Set up Firestore security rules

// For now, this file is a placeholder to prevent compilation errors.
// The app will not work until you configure it with a real Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXBkPd4onlvIEz_LaqdUdHGxW5G529pg',
    appId: '1:273321735011:web:ba20a75d96f3e16cd9d956',
    messagingSenderId: '273321735011',
    projectId: 'module-tracker-tyr',
    authDomain: 'module-tracker-tyr.firebaseapp.com',
    storageBucket: 'module-tracker-tyr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5ODoaN_hbEnGw4bl3lkZ9UkxheA3pyI',
    appId: '1:273321735011:android:a038410b7cd3f25ad9d956',
    messagingSenderId: '273321735011',
    projectId: 'module-tracker-tyr',
    storageBucket: 'module-tracker-tyr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWp19T5Z4n6OyDZuWCsjsvFG8GTlVWAVk',
    appId: '1:273321735011:ios:2c55696979d3c909d9d956',
    messagingSenderId: '273321735011',
    projectId: 'module-tracker-tyr',
    storageBucket: 'module-tracker-tyr.firebasestorage.app',
    iosBundleId: 'com.yourname.moduleTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWp19T5Z4n6OyDZuWCsjsvFG8GTlVWAVk',
    appId: '1:273321735011:ios:2c55696979d3c909d9d956',
    messagingSenderId: '273321735011',
    projectId: 'module-tracker-tyr',
    storageBucket: 'module-tracker-tyr.firebasestorage.app',
    iosBundleId: 'com.yourname.moduleTracker',
  );

}